CREATE DATABASE s22;
CREATE USER s22 WITH ENCRYPTED PASSWORD 's22';
GRANT ALL PRIVILEGES ON DATABASE s22 TO s22;
GRANT CONNECT ON DATABASE s22 TO s22;
\c s22 s22
CREATE TABLE posts (id SERIAL PRIMARY KEY, title VARCHAR, postBody TEXT);